services:
  - type: web
    name: tryp-laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: mysql
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.mailtrap.io
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: "hello@example.com"
      - key: MAIL_FROM_NAME
        value: "${APP_NAME}"
      - key: TURNSTILE_SITE_KEY
        value: ""
      - key: TURNSTILE_SECRET_KEY
        value: ""
      - key: STRIPE_KEY
        value: ""
      - key: STRIPE_SECRET
        value: ""
      - key: STRIPE_WEBHOOK_SECRET
        value: ""

databases:
  - name: tryp-database
    plan: free
    databaseName: tryp
    user: tryp_user 